Adds helm chart for express api.
transmute-industries/transmute-charts pull request #1
Opened 2018-07-09 13:26 UTC by rcstr

2018-07-09 15:59 UTC, OR13 requested changes
can we move all the api node.js dependencies under a root directory `api`, eventually it will need to be moved to its own package in the mono repo. for now, I'd like to keep it isolated from the rest of this charts work.

Please also add a travis test to show the chart deployment succeeds.

2018-07-09 15:59 UTC, OR13 commented on README.md
> +### ipfs
This should say api

2018-07-09 15:59 UTC, OR13 commented on api/values.yaml
> +  repository: nginx
This image should be the docker image built for the node.js api with swagger.

2018-07-09 15:59 UTC, OR13 commented on api/values.yaml
> +  repository: nginx
maybe not, i misread this.

2018-07-09 19:21 UTC, eolszewski commented on package.json
> +  "private": true,
@OR13 do we want these to be private?

2018-07-13 15:38 UTC, OR13 approved these changes

2018-07-13 15:39 UTC, merged